username=root
password=025911
url=jdbc:mysql://localhost:3306/java_wardrobe?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
driver=com.mysql.cj.jdbc.Driver
type=com.alibaba.druid.pool.DruidDataSource

# --- Druid 连接池特有配置 ---
# 初始化连接大小
initialSize=5
# 最小空闲连接数
minIdle=5
# 最大活跃连接数
maxActive=20
# 获取连接等待超时的时间(毫秒)
maxWait=60000
